apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-parcelize'

android {
    namespace "com.animatv.player"
    compileSdkVersion 34
    buildToolsVersion "33.0.2"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
        freeCompilerArgs += ["-opt-in=kotlin.RequiresOptIn"]
    }

    defaultConfig {
        applicationId "com.animatv.player"
        minSdkVersion 21
        targetSdkVersion 34

        versionCode 1
        versionName "1.0"

        multiDexEnabled true

        vectorDrawables {
            useSupportLibrary true
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
    }

    buildFeatures {
        dataBinding true
        viewBinding true
        buildConfig true
    }

    signingConfigs {
        release {
            storeFile file("../animatv.jks")
            storePassword "animatv123"
            keyAlias "animatv"
            keyPassword "animatv123"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false

            proguardFiles(
                getDefaultProguardFile('proguard-android-optimize.txt'),
                'proguard-rules.pro'
            )

            signingConfig signingConfigs.release

            applicationVariants.all { variant ->
                variant.outputs.all {
                    outputFileName =
                            "StarVisionTV_v${defaultConfig.versionName}.apk"
                }
            }
        }

        debug {
            minifyEnabled false
            shrinkResources false
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    packagingOptions {
        exclude 'DebugProbesKt.bin'
        exclude 'kotlin-tooling-metadata.json'
        exclude 'META-INF/*.kotlin_module'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'

        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
    }
}

configurations.all {
    resolutionStrategy.eachDependency { details ->

        def group = details.requested.group
        def name = details.requested.name

        if (group == 'androidx.lifecycle') {
            switch (name) {
                case 'lifecycle-runtime':
                case 'lifecycle-runtime-ktx':
                case 'lifecycle-common':
                case 'lifecycle-common-java8':
                case 'lifecycle-livedata':
                case 'lifecycle-livedata-core':
                case 'lifecycle-livedata-core-ktx':
                case 'lifecycle-viewmodel':
                case 'lifecycle-viewmodel-ktx':
                case 'lifecycle-process':
                case 'lifecycle-viewmodel-savedstate':
                    details.useVersion '2.5.1'
                    break
            }
        }

        if (group == 'androidx.activity') {
            if (name == 'activity' || name == 'activity-ktx') {
                details.useVersion '1.6.1'
            }
        }

        if (group == 'androidx.savedstate') {
            if (name == 'savedstate' || name == 'savedstate-ktx') {
                details.useVersion '1.2.1'
            }
        }

        if (group == 'androidx.fragment') {
            if (name == 'fragment' || name == 'fragment-ktx') {
                details.useVersion '1.5.7'
            }
        }

        if (group == 'androidx.core') {
            if (name == 'core' || name == 'core-ktx') {
                details.useVersion '1.9.0'
            }
        }
    }
}

dependencies {

    implementation fileTree(
        dir: 'libs',
        include: ['*.jar', '*.aar']
    )

    // AndroidX
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
    implementation 'androidx.preference:preference-ktx:1.2.1'

    // Material
    implementation 'com.google.android.material:material:1.8.0'

    // Network
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'org.conscrypt:conscrypt-android:2.5.2'

    // ExoPlayer 2
    implementation 'com.google.android.exoplayer:exoplayer:2.17.1'
    implementation 'com.google.android.exoplayer:exoplayer-core:2.17.1'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.17.1'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.17.1'
    implementation 'com.google.android.exoplayer:exoplayer-smoothstreaming:2.17.1'
    implementation 'com.google.android.exoplayer:exoplayer-rtsp:2.17.1'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.17.1'
    implementation 'com.google.android.exoplayer:extension-okhttp:2.17.1'
    implementation 'com.google.android.exoplayer:extension-mediasession:2.17.1'

    // JSON
    implementation 'com.google.code.gson:gson:2.10.1'

    // UI
    implementation 'com.facebook.shimmer:shimmer:0.5.0'
    implementation 'com.github.bumptech.glide:glide:4.14.2'
    kapt 'com.github.bumptech.glide:compiler:4.14.2'

    implementation 'com.github.ybq:Android-SpinKit:1.4.0'
    implementation 'com.airbnb.android:lottie:3.7.2'

    implementation 'com.github.TutorialsAndroid:FilePicker:v8.0.19'

    // Tests
    testImplementation 'junit:junit:4.13.2'

    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
